.github/ISSUE_TEMPLATE/error-report.md, .github/ISSUE_TEMPLATE/tutorial-request.md
Added default templates for Issues: error report and tutorial request.
=> Update issue templates

_posts/2018-10-31-how-wanikani-works.md, _posts/2018-10-31-unlocking-kanji.md, _posts/2018-10-31-unlocking-vocabulary.md, _posts/2018-11-25-how-do-i-type.md
Fixed a typo in "How WK Works"
Fixed some broken links
Added explanation of small tsu to the "how do I type" page
=> Typo, broken links, small tsu (patch 2)

_posts/2018-11-25-level-up.md, _posts/2018-11-25-reporting-errors.md, _posts/2019-1-17-contact-page.md
- Fixed bad link on contact page
- Corrected typo on level-up page
- Corrected typo on reporting-errors page
---
=> Minor fixes for March 21

_posts/2018-11-25-how-do-i-type.md
Added information about how to type だ行 to the "How to Type" section
=> Added づ section

_posts/2018-11-25-how-do-i-type.md
* Line break formatting was stripped out in the last PR. This should fix that again.
---
=> Fixed line breaks

_posts/2018-11-25-common-mistakes.md
Changed Common Mistakes page title to Why isn't my answer accepted?
---
=> Update title on Common Mistakes page

_posts/2018-11-25-common-mistakes.md
Update Common Mistakes page content to reflect shake animation and message update
---
=> Update Common Mistakes page content

_posts/2018-11-25-small_characters.md
Updated the small characters page to reflect shake animation update
---
=> Update to reflect shake animation

_posts/2018-11-25-double-n.md
Updated Double N page content to reflect changes from shake animation update
---
=> Update Double N page content

_posts/2021-08-18-script-compatibility-mode.md
=> Add fetch changes to script compatibility log

_posts/2021-08-18-script-compatibility-mode.md
**Compatibility Mode Off**: Under lessons, the additional information panels have been redone in React. There are minor markup and visual differences.
=> Script Compatibility Mode v0.7.0: Subject Info Panels

_posts/2021-08-18-script-compatibility-mode.md
**Compatibility Mode Off**: Under lessons, the overlay that appears at the end of a batch of lesson slides has been converted to React.
- This reworks the markup in that overlay, converting the classes to Tailwind, adding ARIA attributes where appropriate, and converting the buttons to buttons.
- It touches how hotkey events are handled so that there aren't collisions or double events.
=> Script Compatibility Mode v1.1.0: Quiz Ready Overlay

_posts/2021-08-18-script-compatibility-mode.md
**Compatibility Mode Off**: Under lessons, the positioning of the batch list navigation has been moved from Javascript (calculations that fire on window resize) to CSS using flexbox and margins.
=> Script Compatibility Mode v1.2.0: Batch List Positioning

_posts/2021-08-18-script-compatibility-mode.md
**Compatibility Mode Off**: Under lessons, we've consolidated the logic for the `Skip` button. It makes it so that the same code drives all the parts of the system that take you to the next item, like keyboard navigation.
=> Script Compatibility Mode v3.1.0: Simplify Skip Button Logic

_posts/2018-10-31-first-reviews.md
Added link to Extra Study page
* Added direct link to the Extra Study page
*
*
=> Added link

_posts/2018-10-31-first-lessons.md
Added link to Extra Study
* Added a link to the Extra Study page
*
*
=> Link update

_posts/2018-11-25-keyboard-shortcuts.md
I included the Lessons related shortcuts alongside the most recent changes we made to the Hotkeys pop-up (for Lessons).
=> Update Keyboard Shortcuts article to reflect Lessons shortcuts

_posts/2020-04-17-review-forecast.md
Removed this sentence: Hovering your mouse over the different numbers shows more information.
=> review-forecast-update: remove sentence

_posts/2022-03-02-extra-study.md
Changed "being seeing" to "see" in the Burned Items section.
=> extra-study-typo-update

_posts/2024-08-25-skip-button.md
Added post for skip button - detailed in this [OKR](https://www.notion.so/tofugu/Knowledge-Guide-Update-Skip-Undo-47b84e805deb48ddb22b31c7f9a4b4a8?pvs=4)
* Added post and content for question "Does WaniKani have a Skip or "I Don't Know" Button?
*
*
=> Added post for skip button

_posts/2018-10-31-wanikani-premium-membership.md
To complete this KR: https://www.notion.so/tofugu/Knowledge-Guide-pricing-page-3b6b5c165d9440c99ca167e5f874aa69?d=12e8c1decb9d8004826d001c5d830c09
Changed pricing page to include tax and vat disclaimer with each price.
=> updated pricing info to include tax and vat info

_posts/2024-11-05-taxes.md
[Based on this KR](https://www.notion.so/tofugu/Knowledge-Guide-tax-page-708390a30f0b49869193a9e4f715740f?d=1308c1decb9d807db970001c4da39222)
The following changes were made:
- add tax page
- write tax page copy based on information from KR
=> Add Tax Page
