Gemfile
Gemfile.lock

Someone approve this if Netlify build passes.

Version lock Ruby to 2.3.6

---

.github/pull_request_template.md
netlify.toml
netlify_headers

* Adds password protection on Netlify PR deploys. This is to block robots from crawling preview sites
* Add credentials to PR template

Add password protection to Netlify PR deploys

---

index.html

* Fix category links on landing page to use explicit slug
---

Fix category links on landing page

---

_posts/2018-11-25-reset-level.md
_posts/2018-11-25-srs-stages.md

Fixes #17 and fixes #18 
* Updated usage of old term **SRS level** to new term **SRS stage**
* Fixed example to show correct decrement count.
* Extended document with more details
---

Update SRS Stage document with fixed example, more details, and using updated term

---

_posts/2018-11-25-subscription-plans.md

Fixes #15
* Update subscription plans copy to correctly state pricing **per year**, not **per month**
---

Fix typo — per year, not per month

---

_sass/header.scss

Closes #24 
* Display hero search regardless of media
---

Display hero search regardless of media

---

netlify.toml

* Run production builds in the production context. Mainly addresses the lack of Google Analytics on the pages because of [the conditional in the default template](https://github.com/tofugu/wanikani-knowledgebase/blob/master/_layouts/default.html#L14) needing a production environment.
---

Set Environment for Production Builds

---

_posts/2018-11-25-srs-stages.md

I updated the SRS stages description to account for an inaccuracy. I changed the amount of time from Guru 1 to Guru 2 from 4 days to 1 week.
* Guru 1 > Guru 2 now says 1 week instead of 4 days
---

Updated Information for SRS stages

---

README.md
_layouts/default.html

* Change User guide to Knowledge Guide on homepage and README
---

Unify naming - to WaniKani Knowledge Guide

---

_posts/2018-11-25-common-mistakes.md

Fixed a typo on the Common Mistakes page with "read".
---

Fix typo "ream", should be "read"

---

Gemfile
Gemfile.lock

Fixes https://github.com/tofugu/wanikani-knowledgebase/issues/52
No need to require a specific Ruby version. Reverting the inclusion back to follow the parent project's pattern of not specifying the Ruby version.
* Remove requiring a specific Ruby version.
---

Remove Ruby version requirement

---

_posts/2021-08-18-script-compatibility-mode.md

Adds description for the legacy and non-legacy pack behavior in lessons and reviews.
---

Update script compatibility log to 0.1.0: legacy and non-legacy packs

---

_posts/2021-08-18-script-compatibility-mode.md

Outlines the changes for the next significant script release.
**Note**: We shouldn’t merge this until tofugu/wanikani#2803 is on production.
---

Bump Script Version to 0.2.0

---

_posts/2021-08-18-script-compatibility-mode.md

- **Compatibility Mode Off**: Submissions to /json/progress are first attempted with fetch and then fall back to $.ajax when unsuccessful

Script Compatibility Mode v0.5.0: Submit review progress with fetch and retry with $.ajax on failure

---

_posts/2021-08-18-script-compatibility-mode.md

- **Compatibility Mode Off**: Marked as a major change, in case there are scripts that rely on the specific review queue updates.
- activeQueue in jStorage will no longer have extra null items. For example if there are only 8 items left, it will be an array of length 8 instead of 10 with 2 items null. 
- arrays are updated using slice() instead of push() and pop()

Update for Script Compatibility v1.0.0: review queue update changes

---

_posts/2021-08-18-script-compatibility-mode.md

- **Compatibility Mode Off**: 
- `$.jStorage.get("reviewQueue")` now contain ids instead of objects.
- The ids are retrieved from `/review/queue?minimal=true`. `/review/queue` still returns the full objects in Compatibility Mode.
- The objects are retrieved in a separate request to `/reviews/items?ids=1,2,3`, which returns the full objects for ids 1,2,3.

Script Compatibility Mode v2.0.0: IDs only in reviewQueue

---

_posts/2021-08-18-script-compatibility-mode.md

**Compatibility Mode Off**: The overlays that appear at the end of the lesson quiz have been converted to React. This does a few things that are breaking changes:
- The overlays no longer have IDs and are styled purely through Tailwind classes.
- Removes the `activateLessonReadyScreen` function from `lessons.js`. That function controlled overlay and button behavior.
- Updates the behavior of `listenStartQuiz` in `quiz.js` to generate and show the next set of lessons.

Script Compatibility Mode v3.0.0: Convert Quiz Overlays to React

---

_posts/2021-08-18-script-compatibility-mode.md

**Compatibility Mode Off**: The navigation for lesson subjects and slides (the bit that lives at the bottom of the lesson slides) has been converted to React.
- As with other changes, IDs have been removed and we're using Tailwind classes for styling.
- The buttons are now `<button>`s, which is nice for all kinds of things, mainly accessibility.
- The logic driving the state of the items lives in jStorage and React and is no longer driven by the classes on the different elements in the list.

Script Compatibility Mode v4.0.0: Update Lesson Slide Navigation

---

_config.yml
_layouts/default.html

This PR updates the google tracking of the knowledge guide to use a new GA4 property as GA3 is being deprecated as of July this year.

update to GA4 tracking

---

_posts/2019-1-17-contact-page.md

- Replaced the dead hyperlink on the Contact Us page in the WKG. The link can be found in the word "here"

Update to Contact Us Page

---

_posts/2022-03-02-extra-study.md

When you get an item incorrect in reviews it shows up in Recent Mistakes. After 24 hours, it is removed from Recent Mistakes.
However, in those 24 hours, if you get that item correct in reviews, it will be removed from Recent Mistakes at that time.
Our Knowledge Guide says the opposite: an item remains in Recent Mistakes for 24 hours even if you get it correct again in reviews. This is false.
This PR changes the information in the Knowledge Guide to reflect how the app actually works.
* Rewrote the sentence of the KG that gives false information.

Correct incorrect information about recent mistakes
